import { Product } from "./types";

export const ITEMS_PER_PAGE = 6;

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "varsity-letterman-classic",
    title: "Varsity Letterman - Classic",
    description: "The icon. Wool body, leather sleeves, snap front.",
    originalPrice: 320,
    salePrice: 189,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=800&auto=format&fit=crop",
    isSale: true,
    isCustomizable: true,
  },
  {
    id: "pro-basketball-jersey",
    title: "Pro Basketball Jersey",
    description: "Tournament-grade mesh. Sublimative team logo.",
    originalPrice: 200,
    salePrice: 149,
    image: "https://images.unsplash.com/photo-1544698310-74ea9d1c8258?q=80&w=800&auto=format&fit=crop",
    isSale: false,
    isCustomizable: true,
  },
  {
    id: "gridiron-football-jersey",
    title: "Gridiron Football Jersey",
    description: "Reinforced shoulders, athletic fit.",
    originalPrice: 350,
    salePrice: 299,
    image: "https://images.unsplash.com/photo-1566933293069-b55c7f326dd4?q=80&w=800&auto=format&fit=crop",
    isSale: false,
    isCustomizable: true,
  },
  {
    id: "basketball-shorts",
    title: "Basketball Shorts",
    description: "Moisture-wicking fabric, lightweight and breathable.",
    originalPrice: 35,
    salePrice: 29,
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop",
    isSale: false,
    isCustomizable: false,
  },
  {
    id: "soccer-cleats",
    title: "Soccer Cleats",
    description: "Aggressive traction, ankle support design.",
    originalPrice: 120,
    salePrice: 88,
    image: "https://images.unsplash.com/photo-1510566337590-2fc1f21d0faa?q=80&w=800&auto=format&fit=crop",
    isSale: false,
    isCustomizable: false,
  },
  {
    id: "tennis-racket",
    title: "Tennis Racket",
    description: "Graphite frame, advanced vibration dampening.",
    originalPrice: 250,
    salePrice: 180,
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=800&auto=format&fit=crop",
    isSale: false,
    isCustomizable: false,
  },
  {
    id: "running-shoes",
    title: "Running Shoes",
    description: "Cushioned sole, supportive arch design.",
    originalPrice: 150,
    salePrice: 98,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800&auto=format&fit=crop",
    isSale: false,
    isCustomizable: false,
  },
  {
    id: "swim-trunks",
    title: "Swim Trunks",
    description: "Quick-dry technology, comfortable fit.",
    originalPrice: 45,
    salePrice: 35,
    image: "https://images.unsplash.com/photo-1501426026826-31c667bdf23d?q=80&w=800&auto=format&fit=crop",
    isSale: false,
    isCustomizable: false,
  },
  {
    id: "yoga-mat",
    title: "Yoga Mat",
    description: "Non-slip surface, eco-friendly materials.",
    originalPrice: 40,
    salePrice: 28,
    image: "https://images.unsplash.com/photo-1592432678016-e910b452f9a2?q=80&w=800&auto=format&fit=crop",
    isSale: false,
    isCustomizable: false,
  }
];
